"""PD_goal_oriented_delegation_1st pages: shared global pages + local goal-oriented page."""

from pages_classes import (
    BatchWaitForGroup,
    BotDetection,
    ComprehensionTest,
    Debriefing,
    DecisionNoDelegation,
    DelegationDecision,
    ExitQuestionnaire,
    FailedTest,
    GuessDelegation,
    InformedConsent,
    InstructionsDelegation,
    InstructionsGuessingGame,
    InstructionsNoDelegation,
    InstructionsOptional,
    MainInstructions,
    Results,
    ResultsGuess,
    Thankyou,
    TimeOutquit,
)

from .goalOriented import GoalOriented

page_sequence = [
    InformedConsent,
    BotDetection,
    MainInstructions,
    ComprehensionTest,
    FailedTest,
    InstructionsNoDelegation,
    InstructionsDelegation,
    InstructionsOptional,
    DelegationDecision,
    DecisionNoDelegation,
    GoalOriented,
    BatchWaitForGroup,
    TimeOutquit,
    Results,
    InstructionsGuessingGame,
    GuessDelegation,
    ResultsGuess,
    Debriefing,
    ExitQuestionnaire,
    BotDetection,
    Thankyou,
]

__all__ = [
    "GoalOriented",
    "BatchWaitForGroup",
    "BotDetection",
    "ComprehensionTest",
    "Debriefing",
    "DecisionNoDelegation",
    "DelegationDecision",
    "ExitQuestionnaire",
    "FailedTest",
    "GuessDelegation",
    "InformedConsent",
    "InstructionsDelegation",
    "InstructionsGuessingGame",
    "InstructionsNoDelegation",
    "InstructionsOptional",
    "MainInstructions",
    "Results",
    "ResultsGuess",
    "Thankyou",
    "TimeOutquit",
    "page_sequence",
]
